### PaymentsService API Tests ###

@paymentsHost = http://localhost:5001
@userId = 3fa85f64-5717-4562-b3fc-2c963f66afa6


###
# Создание нового счета для пользователя
# Ожидаемый ответ: 201 Created с ID нового счета
POST {{paymentsHost}}/api/accounts
Content-Type: application/json

{
  "userId": "{{userId}}"
}


###
# Попытка создать еще один счет для того же пользователя
# Ожидаемый ответ: 409 Conflict с сообщением об ошибке
POST {{paymentsHost}}/api/accounts
Content-Type: application/json

{
  "userId": "{{userId}}"
}


###
# Пополнение существующего счета
# Ожидаемый ответ: 200 OK
POST {{paymentsHost}}/api/accounts/deposit
Content-Type: application/json

{
  "userId": "{{userId}}",
  "amount": 150.75
}


###
# Попытка пополнить несуществующий счет
# Ожидаемый ответ: 404 Not Found
POST {{paymentsHost}}/api/accounts/deposit
Content-Type: application/json

{
  "userId": "00000000-0000-0000-0000-000000000000",
  "amount": 100.00
}


###
# Попытка пополнить счет на отрицательную сумму
# Ожидаемый ответ: 400 Bad Request с ошибкой валидации
POST {{paymentsHost}}/api/accounts/deposit
Content-Type: application/json

{
  "userId": "{{userId}}",
  "amount": -50.00
}


###
# Получение информации о счете по ID пользователя
# Ожидаемый ответ: 200 OK с данными счета
GET {{paymentsHost}}/api/accounts/user/{{userId}}


###
# Получение информации о несуществующем счете по ID пользователя
# Ожидаемый ответ: 404 Not Found
GET {{paymentsHost}}/api/accounts/user/00000000-0000-0000-0000-000000000001


###
# Получение информации о счете по его собственному ID
# Ожидаемый ответ: 200 OK
GET {{paymentsHost}}/api/accounts/4db69e11-60fb-484f-8568-b1109414953c