services:

  apigateway:
    image:
      name: apigateway
      tag: latest
    container_name: apigateway
    build:
      context: ./APIGateway
      dockerfile: APIGateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - API_PORT=80
      - ReverseProxy__Clusters__orders__Destinations__orders__Address=http://ordersservice:80
      - ReverseProxy__Clusters__payments__Destinations__payments__Address=http://paymentsservice:80
    networks:
      - orders_payments_network
    depends_on:
      - paymentsservice
      - ordersservice
    restart: on-failure

  ordersservice:
    image:
      name: ordersservice
      tag: latest
    container_name: ordersservice
    build:
      context: ./OrdersService
      dockerfile: OrdersService/Dockerfile
    ports:
      - "${ORDERS_SERVICE_PORT:-5002}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - API_PORT=80
      - ConnectionStrings__PostgreSQL=Host=ordersservicepostgres;Port=5432;Database=${ORDERS_SERVICE_POSTGRES_DB_NAME};Username=${ORDERS_SERVICE_POSTGRES_USER};Password=${ORDERS_SERVICE_POSTGRES_PASSWORD}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASSWORD}
    networks:
      - orders_payments_network
    depends_on:
      ordersservicepostgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: on-failure

  paymentsservice:
    image:
      name: paymentsservice
      tag: latest
    container_name: paymentsservice
    build:
      context: ./PaymentsService
      dockerfile: PaymentsService/Dockerfile
    ports:
      - "${PAYMENTS_SERVICE_PORT:-5001}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - API_PORT=80
      - ConnectionStrings__PostgreSQL=Host=paymentsservicepostgres;Port=5432;Database=${PAYMENTS_SERVICE_POSTGRES_DB_NAME};Username=${PAYMENTS_SERVICE_POSTGRES_USER};Password=${PAYMENTS_SERVICE_POSTGRES_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - orders_payments_network
    depends_on:
      paymentsservicepostgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: on-failure

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_MAIN_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - orders_payments_network
    restart: on-failure

  ordersservicepostgres:
    container_name: ordersservicepostgres
    image: postgres:latest
    ports:
      - "${ORDERS_SERVICE_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${ORDERS_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDERS_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDERS_SERVICE_POSTGRES_DB_NAME}
    networks:
      - orders_payments_network
    volumes:
      - orders_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ORDERS_SERVICE_POSTGRES_USER} -d ${ORDERS_SERVICE_POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  paymentsservicepostgres:
    container_name: paymentsservicepostgres
    image: postgres:latest
    ports:
      - "${PAYMENTS_SERVICE_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${PAYMENTS_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PAYMENTS_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${PAYMENTS_SERVICE_POSTGRES_DB_NAME}
    networks:
      - orders_payments_network
    volumes:
      - payments_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PAYMENTS_SERVICE_POSTGRES_USER} -d ${PAYMENTS_SERVICE_POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  orders_payments_network:
    name: orders_payments_network

volumes:
  payments_data:
  orders_data: