### OrdersService API Tests ###

@ordersHost = http://localhost:5002
@userId = 3fa85f64-5717-4562-b3fc-2c963f66afa6


###
# Создание нового заказа
# Ожидаемый ответ: 201 Created с ID нового заказа
POST {{ordersHost}}/api/orders
Content-Type: application/json

{
  "userId": "{{userId}}",
  "amount": 50.25,
  "description": "Книга про Clean Architecture"
}


###
# Получение списка всех заказов для пользователя
# Ожидаемый ответ: 200 OK с массивом заказов
GET {{ordersHost}}/api/orders?userId={{userId}}


###
# Получение конкретного заказа по его ID
# Ожидаемый ответ: 200 OK с данными заказа.
GET {{ordersHost}}/api/orders/f54e405f-c520-4347-9b34-e742f14e3e12


###
# Попытка получить несуществующий заказ
# Ожидаемый ответ: 404 Not Found
GET {{ordersHost}}/api/orders/00000000-0000-0000-0000-000000000000


###
# Отмена заказа
# Ожидаемый ответ: 204 NoContent
PATCH {{ordersHost}}/api/orders/f54e405f-c520-4347-9b34-e742f14e3e12/cancel


###
# Создание заказа с некорректными данными (отрицательная сумма)
# Ожидаемый ответ: 400 Bad Request с ошибками валидации
POST {{ordersHost}}/api/orders
Content-Type: application/json

{
  "userId": "{{userId}}",
  "amount": -100,
  "description": "Попытка взломать систему"
}